### PR TITLE
fix: Remove stage_file_proxy, so Jenkins can manage it independently.

### PR DESCRIPTION
**Pull request by cafuego**

### CODE REVIEW

**Review by lazysoundsystem — APPROVED** [review]
Reluctant approval - I'll try to find a way to handle this alongside config_split for local development...

**Comment by attiks** [comment]
You can move it to require-dev?

**Comment by cafuego** [comment]
If it's in require-dev I can *only* enable it on the dev/demo sites by running `composer install --dev` and that also installs all the other dev guff. 

I guess we could do that, but I'm not 100% happy about it.

**Comment by lazysoundsystem** [comment]
I'd be happier with that. Could a half-way point be to do `composer install` and then a separate `composer require drupal/stage_file_proxy`?

**Pull request closed without merging**
