### PR TITLE
Feature/20230802 d10

### PR DESCRIPTION
**Pull request by attiks**

### CODE REVIEW

**Review by lazysoundsystem — APPROVED** [review]
All looks good, but not sure why we're removing config_split and environment_indicator.

**Comment by attiks** [comment]
I had a hard time getting it deployed, it seemed like the dev deploy tried to enable all dev modules

**Comment by lazysoundsystem** [comment]
I can try to put them back if that's okay. Or I can do that in a separate PR if you'd prefer.

Also, CKEditor 4 is deprecated and we should be moving to CKEditor 5, which is in core: https://github.com/UN-OCHA/iasc8/pull/822

**Comment by attiks** [comment]
Best in a separate one, feel free to do ckeditor 5 as well

**Pull request merged**
