### PR TITLE
[OPS-7634] add fix for composer-patches

### PR DESCRIPTION
**Pull request by lazysoundsystem**
As suggested in https://github.com/UN-OCHA/iasc8/pull/506

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
Not sure what's happening here - the error comes after the paragraphs module is installed in `drush cim`, when iasc_content wants to 'use' one of its classes:
```
Error: Class 'Drupal\paragraphs\Event\ParagraphSummaryAlterEvent' not found in /home/travis/build/UN-OCHA/iasc8/html/modules/custom/iasc_content/src/EventSubscriber/ParagraphSummaryAlter.php on line 36 #0 /home/travis/build/UN-OCHA/iasc8/html/core/lib/Drupal/Core/DependencyInjection/Compiler/RegisterEventSubscribersPass.php(37): Drupal\iasc_content\EventSubscriber\ParagraphSummaryAlter::getSubscribedEvents()
```
And not sure which of the very few changes since https://github.com/UN-OCHA/iasc8/pull/505 could be causing this.

**Comment by attiks** [comment]
> ParagraphSummaryAlterEvent

This is from a patch, https://www.drupal.org/project/paragraphs/issues/2868252. Is it still applied?

**Comment by lazysoundsystem** [comment]
That will be it - the change was to composer-patches, which appears not to be doing the right thing here. I hadn't realized that class was introduced in a patch - thanks for saving a lot of time!

**Comment by lazysoundsystem** [comment]
Plenty more information in https://app.travis-ci.com/github/UN-OCHA/iasc8/builds/234096345 - it mentions getting cweagans/composer-patches but not about taking any action. 

I tried reverting the composer-patches swap, which does apply the patches, so there seems to be a conflict between what travis expects from composer-patches and what github expects.

**Comment by lazysoundsystem** [comment]
Closing as the failing test is now gone from https://github.com/UN-OCHA/iasc8/pull/506

**Pull request closed without merging**
