### PR TITLE
[OPS-7634] update core to 8.9.17

### PR DESCRIPTION
**Pull request by lazysoundsystem**
https://humanitarian.atlassian.net/browse/OPS-7634

Plus update for composer (to v2) and php (to 7.4).

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
@cafuego the errors here are from the outdated.yml script - I'm not sure why the patches don't apply there when they do apply locally - do you have any ideas?

**Comment by cafuego** [comment]
Yes, though it took me ages to figure it out - https://github.com/cweagans/composer-patches/pull/375

**Comment by lazysoundsystem** [comment]
@cafuego I tried the patch to composer-patches in https://github.com/UN-OCHA/iasc8/pull/508, but then it fails the travis tests as the patches aren't present. I can't see a way forward on this.

**Comment by cafuego** [comment]
The outdated.yml run failure is a red herring and should not block work. I have removed the run-on-pr-against-develop setting.

**Comment by lazysoundsystem** [comment]
@left23 just checking that you're expecting the above changes to be deployed.

**Review by left23 — APPROVED** [review]
All good, thanks

**Pull request merged**
